package co.edu.uptc.tiendaminorista.enums;

public enum CategoriaProducto {
    GRANOS, LACTEOS, CARNES, PESCADOS, MARISCOS, EMBUTIDOS,
    VERDURAS, FRUTAS, PANADERIA, REPOSTERIA, HUEVOS,
    BEBIDAS, GASEOSAS, JUGOS, AGUA, ENERGETICAS, LICOR, CAFE, TE,
    CONGELADOS, COMIDA_PREPARADA, ENLATADOS, SNACKS, DULCES,
    CEREALES, PASTAS, SALSAS, CONDIMENTOS,
    ASEO, LIMPIEZA_HOGAR, PAPELERIA, DESECHABLES,
    HIGIENE_PERSONAL, COSMETICOS, CUIDADO_CAPILAR, PERFUMERIA,
    MASCOTAS, ALIMENTO_MASCOTAS,
    MEDICAMENTOS, SUPLEMENTOS,
    ELECTRONICA, JUGUETES, ROPA, FERRETERIA, OFICINA, OTROS;
}
